### PR TITLE
Allow setting custom cache path and file prefix

### PR DESCRIPTION
**Pull request by Twixes**
I have a use case where I need to have the query cache in a specific directory. This adds an option to `DefaultQueryRunner` called `cache_path`, allowing exactly this.

### CODE REVIEW

**Comment by timwie** [comment]
Thank you for the contribution! Seems like a good idea to put this into `DefaultQueryRunner`, as it doesn't really warrant me telling you to implement your own `QueryRunner` for these few changes.

If you want to, you can also update the CHANGELOG.md and attribute the change to yourself (linking you Github profile or something, idk)

**Comment by timwie** [comment]
I can help look at why the test fails next week.

CI also complains about the formatting. If you install all the dev dependencies, you can run `invoke fmt` and will fix that.

**Comment by Twixes** [comment]
Thanks! Formatted the code. Don't know what causes the test failures though 🤔

**Comment by timwie** [comment]
It happens because CI runs the tests in parallel, and all three tests in `test_default_query_runner.py` have the same cache key, and work on the same file path. You should change the `"nonsense"` in `Query(input_code="nonsense")` to something else in each test function. Then it should work.

The linter also complains, changing the `Optional[str]` stuff like I said above fixes one issue. The other linting error is that `__init__` has too many arguments. I'm fine with just changing `max-args = 4` in `pyproject.toml` to

```
[tool.ruff.lint.pylint]
max-args = 5
```

**Comment by timwie** [comment]
I'll close this since it has been inactive for a while. I've made some changes in 706dc45 that should make it easier to  cache to another path by extending `DefaultQueryRunner` and overriding the `_cache_file_name()` and `_cache_file_path()` functions. That will land in release 0.14. Thanks again for the contribution.

**Pull request closed without merging**
